### ISSUE TITLE
Crash on function definition

### ISSUE THREAD

**Issue by maxlor** [maxlor/mcalc#2]
```
> f(x,y)=e^(x/(y))
Traceback (most recent call last):
  File "C:\msys64\home\lutz-8\bin\mcalc", line 1371, in <module>
    main()
  File "C:\msys64\home\lutz-8\bin\mcalc", line 1365, in main
    calculator.run()
  File "C:\msys64\home\lutz-8\bin\mcalc", line 200, in run
    _showResults(self.calc(line))
  File "C:\msys64\home\lutz-8\bin\mcalc", line 151, in calc
    parsedObjects = self._parser.parse(lexerStream)
  File "C:/msys64/mingw64/lib/python3.9/site-packages/rply/parser.py", line 49, in parse
    current_state = self._reduce_production(
  File "C:/msys64/mingw64/lib/python3.9/site-packages/rply/parser.py", line 80, in _reduce_production
    value = p.func(targ)
  File "C:\msys64\home\lutz-8\bin\mcalc", line 617, in assignment_openFunction_argumentList
    return _addFunction(p[0].value, p[1], p[4])
AttributeError: 'str' object has no attribute 'value'
```

**Comment by maxlor** [comment]
Seems to have been fixed at some point.
